export const LANGUAGE_COLORS: Record<string, string> = {
  typescript: "#3178C6",
  javascript: "#F7DF1E",
  python: "#3572A5",
  rust: "#DEA584",
  go: "#00ADD8",
  java: "#B07219",
  csharp: "#178600",
  cpp: "#F34B7D",
  c: "#555555",
  ruby: "#701516",
  php: "#4F5D95",
  swift: "#F05138",
  kotlin: "#A97BFF",
  html: "#E34C26",
  css: "#563D7C",
  scss: "#C6538C",
  json: "#A4A4A4",
  yaml: "#CB171E",
  markdown: "#083FA1",
  dockerfile: "#384D54",
  shell: "#89E051",
  sql: "#E38C00",
  lua: "#000080",
  dart: "#00B4AB",
  vue: "#41B883",
  svelte: "#FF3E00",
  unknown: "#888888",
};

export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  ".ts": "typescript",
  ".tsx": "typescript",
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".py": "python",
  ".rs": "rust",
  ".go": "go",
  ".java": "java",
  ".cs": "csharp",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".h": "c",
  ".c": "c",
  ".rb": "ruby",
  ".php": "php",
  ".swift": "swift",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".html": "html",
  ".htm": "html",
  ".css": "css",
  ".scss": "scss",
  ".sass": "scss",
  ".json": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".md": "markdown",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".sql": "sql",
  ".lua": "lua",
  ".dart": "dart",
  ".vue": "vue",
  ".svelte": "svelte",
};

export function getLanguage(extension: string, filename: string): string {
  if (filename.toLowerCase() === "dockerfile") return "dockerfile";
  return EXTENSION_TO_LANGUAGE[extension.toLowerCase()] ?? "unknown";
}

export function getColor(language: string): string {
  return LANGUAGE_COLORS[language] ?? LANGUAGE_COLORS.unknown;
}
