import type { PerlerColor } from "./perler-palette.js";

export const LANGUAGE_PERLER: Record<string, PerlerColor> = {
  typescript: "blue",
  javascript: "yellow",
  python: "skyBlue",
  rust: "tan",
  go: "mint",
  java: "pumpkin",
  csharp: "purple",
  cpp: "hotCoral",
  c: "darkGrey",
  ruby: "darkRed",
  php: "periwinkle",
  swift: "orange",
  kotlin: "lavender",
  html: "lightOrange",
  css: "cobalt",
  scss: "magenta",
  json: "lightGrey",
  yaml: "red",
  markdown: "pastelBlue",
  dockerfile: "navy",
  shell: "lightGreen",
  sql: "cheddar",
  lua: "darkBlue",
  dart: "skyBlue",
  vue: "green",
  svelte: "salmon",
  toml: "tan",
  xml: "peach",
  unknown: "grey",
};

export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  ".ts": "typescript",
  ".tsx": "typescript",
  ".js": "javascript",
  ".jsx": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".py": "python",
  ".rs": "rust",
  ".go": "go",
  ".java": "java",
  ".cs": "csharp",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".h": "c",
  ".c": "c",
  ".rb": "ruby",
  ".php": "php",
  ".swift": "swift",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".html": "html",
  ".htm": "html",
  ".css": "css",
  ".scss": "scss",
  ".sass": "scss",
  ".json": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".md": "markdown",
  ".markdown": "markdown",
  ".sh": "shell",
  ".bash": "shell",
  ".zsh": "shell",
  ".sql": "sql",
  ".lua": "lua",
  ".dart": "dart",
  ".vue": "vue",
  ".svelte": "svelte",
  ".toml": "toml",
  ".xml": "xml",
};

export function getLanguage(extension: string, filename: string): string {
  if (filename.toLowerCase() === "dockerfile") return "dockerfile";
  return EXTENSION_TO_LANGUAGE[extension.toLowerCase()] ?? "unknown";
}

export function getPerlerColor(language: string): PerlerColor {
  return LANGUAGE_PERLER[language] ?? "grey";
}
